# Generated by Django 4.2.11 on 2024-03-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=255)),
                ('platformIcon', models.ImageField(upload_to='')),
                ('profileUrl', models.URLField()),
                ('featured', models.BooleanField(db_index=True)),
            ],
        ),
    ]
