# Generated by Django 4.2.11 on 2024-03-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_alter_socialplatformsmodel_platformicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel')),
            ],
        ),
    ]
