# Generated by Django 4.2.11 on 2024-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0005_educationinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currently_working', models.BooleanField(db_index=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='company_logo/')),
                ('company_website', models.URLField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
