# Generated by Django 4.2.11 on 2024-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0007_alter_experienceinfomodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfomodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
