# Generated by Django 4.2.11 on 2024-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0008_alter_experienceinfomodel_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('course_badge', models.ImageField(blank=True, upload_to='certificate_badge/')),
                ('featured', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
