# Generated by Django 4.2.11 on 2024-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0010_skillsinfomodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsinfomodel',
            name='featured',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
