# Generated by Django 4.2.11 on 2024-03-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0011_skillsinfomodel_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorProjectsInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(db_index=True)),
                ('project_url', models.URLField(blank=True)),
                ('project_logo', models.ImageField(blank=True, upload_to='projects_logo/')),
                ('featured', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
