# Generated by Django 4.2.11 on 2024-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0013_resumeuploadmodel_video_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
