# Generated by Django 4.2.11 on 2024-03-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0014_alter_userprofilemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatformsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
    ]
