# Generated by Django 4.2.11 on 2024-03-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0015_socialplatformsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialplatformsmodel',
            old_name='user',
            new_name='user_profile',
        ),
    ]
