# Generated by Django 4.2.11 on 2024-03-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0016_rename_user_socialplatformsmodel_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinfomodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationinfomodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceinfomodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorprojectsinfomodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillsinfomodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.userprofilemodel'),
            preserve_default=False,
        ),
    ]
