# Generated by Django 4.2.11 on 2024-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0017_certificateinfomodel_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeuploadmodel',
            name='cover_letter',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeuploadmodel',
            name='designation',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
