# Generated by Django 4.2.11 on 2024-03-26 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0018_resumeuploadmodel_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsinfomodel',
            name='proficiency',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
